apiVersion: v1
kind: Template
metadata:
  name: scrape-prometheus-job
parameters:
- description: The name for job
  from: 'scrape-prometheus-[a-z0-9]{4}'
  generate: expression
  name: APPLICATION_NAME
  required: true
- name: URL
  description: URL of prometheus server
  required: true
- name: BEARER_TOKEN
  description: Bearer Token for accessing prometheus
  required: true
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    containers:
    - image: durandom/scrape-prometheus
      name: "${APPLICATION_NAME}"
      imagePullPolicy: Always
#          terminationMessagePath: /dev/termination-log
#          terminationMessagePolicy: File
      concurrencyPolicy: Forbid
      resources:
        limits:
          cpu: '1'
          memory: 2Gi
        requests:
          cpu: '1'
          memory: 2Gi
      env:
      - name: PROM_BACKUP_ALL
        value: "true"
      - name: BEARER_TOKEN
        value: "${BEARER_TOKEN}"
      - name: URL
        value: "${URL}"
    restartPolicy: Never
